task:
  name: Unit tests and widget tests
  env:
    matrix:
      template: material_bottomnavigation_provider_mobx
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd $template
    - flutter test

task:
  name: Integration tests (Android)
  env:
    EMULATOR_API_LEVEL: 22
    ANDROID_ABI: "default;armeabi-v7a"
    matrix:
      template: material_bottomnavigation_provider_mobx
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  create_native_projects_script:
    - cd $template
    - flutter create .
  create_device_script:
    echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
  wait_for_emulator_script:
    - adb wait-for-device
    - adb shell input keyevent 82
  test_script:
    flutter drive --target=test_driver/app.dart

