create_native_projects_task:
  container:
    image: cirrusci/flutter:stable
  create_script: flutter create .

build_material_bottomnavigation_provider_mobx_task:
  depends_on: create_native_projects_task
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter build apk

build_material_bottomnavigation_provider_mobx_task:
  depends_on: create_native_projects_task
  osx_instance:
    image: mojave-xcode-10.2-flutter
  pub_cache:
    folder: ~/.pub-cache
  update_pods_script: pod repo update # to fetch all the latest versions
  build_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter build ios --no-codesign

test_material_bottomnavigation_provider_mobx_task:
  depends_on: create_native_projects_task
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter test test/**/*.dart
    - flutter drive --target=test_driver/app.dart