create_material_bottomnavigation_provider_mobx_native_projects_task:
  container:
    image: cirrusci/flutter:stable
  create_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter create .

# build_material_bottomnavigation_provider_mobx_android_task:
#   depends_on: create_material_bottomnavigation_provider_mobx_native_projects_task
#   container:
#     image: cirrusci/flutter:stable
#   pub_cache:
#     folder: ~/.pub-cache
#   build_script:
#     - cd material_bottomnavigation_provider_mobx
#     - flutter build apk

# build_material_bottomnavigation_provider_mobx_ios_task:
#   depends_on: create_material_bottomnavigation_provider_mobx_native_projects_task
#   osx_instance:
#     image: mojave-xcode-10.2-flutter
#   pub_cache:
#     folder: ~/.pub-cache
#   update_pods_script: pod repo update # to fetch all the latest versions
#   build_script:
#     - cd material_bottomnavigation_provider_mobx
#     - flutter build ios --no-codesign

unit_widget_tests_material_bottomnavigation_provider_mobx_task:
  depends_on: create_material_bottomnavigation_provider_mobx_native_projects_task
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter test test/**/*.dart

integration_tests_material_bottomnavigation_provider_mobx_task:
  depends_on: create_material_bottomnavigation_provider_mobx_native_projects_task
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  create_device_script: >
    echo no | avdmanager create avd --force \
      -n test \
      k "system-images;android-28;default;armeabi-v7a"
  start_emulator_background_script:
    - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window
  wait_for_emulator_script: adb wait-for-device
  test_script:
    - cd material_bottomnavigation_provider_mobx
    - flutter drive --target=test_driver/app.dart


