task:
  name: Unit tests and widget tests
  env:
    matrix:
      template: material_bottomnavigation_provider_mobx
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd $template
    - flutter test

